### ISSUE TITLE
editorjs@latest:6 Module Tools was skipped because of Error: Tool «editorJSStyle» must be a constructor function or an object with function in the «class» property

### ISSUE THREAD

**Issue by diadjii** [hata6502/editorjs-style#25]
Hi i have this error after adding editorjs style plugin tool, can you help me I can't resolve  this

**Comment by hata6502** [comment]
latest version v3.0.0 includes the breaking change of module imports. 

https://github.com/hata6502/editorjs-style/releases/tag/v3.0.0

Try it: 
```
      const editorJS = new EditorJS({
        data,
        tools: {
          style: EditorJSStyle.StyleInlineTool,
        },
      })
```

example: https://github.com/hata6502/editorjs-style/blob/master/docs/index.html#L36

**Comment by diadjii** [comment]
it's works thank you
